# See https://github.com/JuliaLang/Example.jl/blob/master/.appveyor.yml

environment:
  matrix:
  - julia_version: 1.0  # LTS release
  - julia_version: 1.4  # Current stable release
  - julia_version: nightly

matrix:
  allow_failures:
  - julia_version: nightly

platform:
- x86
- x64

branches:
  only:
  - master
  - /release-.*/

notifications:
- provider: Email
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false

install:
- ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
- echo "%JL_BUILD_SCRIPT%"
- C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
- echo "%JL_TEST_SCRIPT%"
- C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
