## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

git:
  depth: 99999999

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  # push coverage results
  - julia -e 'cd(Pkg.dir("QueryCombinators")); include("test/coverage.jl")'
  # deploy documentation
  - julia -e 'cd(Pkg.dir("QueryCombinators")); include("doc/make.jl")'
