# See https://github.com/JuliaLang/Example.jl/blob/master/.travis.yml

language: julia

os:
- linux
- osx

julia:
- 1.0   # LTS release
- 1.1   # Current stable release
- nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

env:
  global:
  - DOCUMENTER_DEBUG=true

script:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
- julia --color=yes -e 'using Pkg; Pkg.clone("https://github.com/rbt-lang/PrettyPrinting.jl"); Pkg.build(); Pkg.add("Random"); Pkg.test(coverage=true)'

after_success:
# push coverage results
- julia -e 'using Pkg; cd(Pkg.dir("DataKnots")); include("test/coverage.jl")'

jobs:
  include:
  # deploy documentation
  - stage: "Documentation"
    os: linux
    julia: 1.0
    script:
    - julia -e 'using Pkg; Pkg.clone("https://github.com/rbt-lang/PrettyPrinting.jl"); cd(Pkg.dir("DataKnots")); include("doc/make.jl")'
    after_success: skip
