name = "DataKnots"
uuid = "f3f2b2ad-91c8-5588-b964-d77e2d3bb090"
authors = ["Kirill Simonov <xi@resolvent.net>", "Clark C. Evans <cce@clarkevans.com"]
version = "0.2.0"

[deps]
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[targets]
test = ["NarrativeTest", "Pkg", "Random", "Statistics"]
