name = "DataKnots"
uuid = "f3f2b2ad-91c8-5588-b964-d77e2d3bb090"
authors = ["Kirill Simonov <xi@resolvent.net>", "Clark C. Evans <cce@clarkevans.com"]
version = "0.10.0"

[deps]
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"               # [1.0.0, 2.0.0)
Tables = "1.0.1"          # [1.0.1, 2.0.0)
PrettyPrinting = "0.2.0"  # [0.2.0, 0.3.0)

[targets]
test = ["NarrativeTest", "Random", "Statistics", "DataFrames", "CSV"]
